version: '3.4'

volumes:
  mysql-data:

networks:
  security-api:
    driver: bridge

services:
  mongo:
    image: mongo:5.0
    container_name: mongo
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
        - MONGO_INITDB_DATABASE=admin
    restart: unless-stopped
    networks:
      - security-api
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017
      #- ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      #- ME_CONFIG_BASICAUTH_USERNAME=mexpress
      #- ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    networks:
      - security-api
    links:
      - mongo
    restart: always
    ports:
      - "8081:8081"